<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BootstrapBlazor" Version="9.1.0" />
    <PackageReference Include="BootstrapBlazor.DataAccess.FreeSql" Version="9.0.0" />
    <PackageReference Include="FreeSql.Provider.Sqlite" Version="3.5.102" />
    <PackageReference Include="Longbow.Tasks" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DispatchManager.Caching\DispatchManager.Caching.csproj" />
  </ItemGroup>

</Project>
